import sys 

sys.path.insert(0, '/Users/mac/Documents/GitHub/SoftEngProject/tradetalker')

from python_component.nltk_component.preprocessing import GetPOSClass, PreprocessText
pos = GetPOSClass()
p = PreprocessText(pos)

#mock article data
class Article:
    def __init__(self, id: int, header: str, content: str, labelled_sentiment: str):
        self.ArticleID = id 
        self.header = header 
        self.Content = content 
        self.ProcessedArticle = p.preprocess_text(content)
        self.sentiment = labelled_sentiment


content1 = """Google has invested $1bn (£790m) to build its first UK data centre.
The tech giant said construction had started at a 33-acre site in Waltham Cross, Hertfordshire, and hoped it would be completed by 2025.
Google stressed it was too early to say how many jobs would be created but it would need engineers, project managers, data centre technicians, electricians, catering and security personnel.
The prime minister said it showed the UK had "huge potential for growth".
The project marked the latest investment by a major US tech firm in Britain, after Microsoft announced it would invest £2.5bn to expand data centres for artificial intelligence (AI) across the UK. Prime Minister Rishi Sunak hailed the investment as proof the UK has "huge potential" as a technology hub
The new Hertfordshire facility would add to Google's 27 data centres worldwide, with sites across 11 countries and 13 in the US.
It said the site would help power popular digital services, such as Google Cloud, Gmail, Docs, Sheets, search and maps.
It would also "play a critical role in supporting the company's AI innovations and will provide the UK with much-needed compute capacity".
Google said the facility would be constructed in line with net-zero aims and it planned for significant heat generated by the data centre to be used to heat homes and businesses in the local area.
'Growing demand'
Google already has more than 7,000 staff in the UK and sites in King's Cross, Central Saint Giles and Victoria in London and Manchester.
Its DeepMind AI research and development lab is also based in London.
Ruth Porat, president, chief investment officer and chief financial officer of Google, said: "This new data centre will help meet growing demand for our AI and cloud services".
She said it would "bring crucial compute capacity to businesses across the UK while creating construction and technical jobs for the local community."
A sign near the Google's headquarters in Mountain View, California
Google said it was too early to say how many jobs the site
Prime Minister Rishi Sunak said: "Foreign investment creates jobs and grows all regions of our economy, and investments like this will help to drive growth in the decade ahead."
Chancellor Jeremy Hunt, who was at the World Economic Forum in Davos, Switzerland, added: "From business conducted online to advancements in healthcare, every growing economy relies on data centres.
"Our country is no different and this major $1bn investment from Google is a huge vote of confidence in Britain as the largest tech economy in Europe."
"""
article1 = Article(1, "Google has invested $1bn (£790m) to build its first UK data centre", content1, 'positive')


content2 = """
Microsoft looks beyond Xbox hardware for gaming growth: Microsoft is accelerating a push away from its own Xbox hardware, hoping to boost growth by selling more games on rival consoles as the industry reckons with a protracted slowdown.
The technology group plans to make a handful of games that were previously offered only on its Xbox available on Sony’s PlayStation and Nintendo’s Switch, in a departure from its previous strategy of keeping games developed in-house as exclusives for its own platforms.
Four months after closing its $75bn Activision Blizzard deal, Microsoft also said the first title from the portfolio of the Call of Duty creator would start appearing on its Game Pass subscription service next month.
Phil Spencer, chief executive of Microsoft Gaming, insisted the moves were “not a change to our fundamental exclusives strategy” but reflected a desire to expand the audience for certain games that have hit a ceiling on its own platforms.
In an interview with the Financial Times, Spencer said there was “some diminishing return” from focusing only on selling more games to its existing audience of Xbox owners.
“When I look forward, for our business, finding more players in more places, many of them on the devices that they already own, is a good thing for our own growth as well,” he said.
Content delivers higher margins than hardware for Microsoft, Spencer said, adding: “Extending the software and services and games to more endpoints improves the overall profitability of the [Xbox] division.”
The latest Xbox console generation, first released in 2020, has struggled to keep up with the PlayStation 5 and Switch. Some analysts estimate PS5 outsold Xbox by almost three to one last year, but both have been comprehensively outsold by the older Switch over its lifetime.
“We have more Xbox players off of Xbox consoles than on Xbox consoles today,” Spencer said, referring to those who play its games on PCs or other devices via cloud streaming. “Those lines will continue to diverge. That’s a good thing for the health of the business because the hardware we sell is not a profit driver for us in our organisation.”
Sony announced in December that PS5 hit a milestone of 50mn sales, but the Japanese group nevertheless this week downgraded 2024 forecasts for its gaming unit, as a new wave of lay-offs hit games developers across the industry in the first weeks of the year.
Enders Analysis estimates global gaming revenue rose by less than 1 per cent last year to $184bn, a slower rate than inflation. Enders’ researchers said in a recent report that 2024 was set to be a “bumpy and uncomfortable year across the industry” as “revenue growth is likely to be flat for the next 12-24 months”.
Microsoft is among those cutting jobs, saying last month it would lay off around 1,900 staff, or about 8 per cent of its gaming workforce, including some at Activision Blizzard.
Microsoft has for several years pushed its subscription service, Game Pass, which is available on Xbox and PC but not on PlayStation. About 34mn people subscribe to Game Pass, which costs $17 a month for full access to the latest games on consoles and PC, or less for access to a limited catalogue and multiplayer features.
"""

article2 = Article(2, "Microsoft looks beyond Xbox hardware for gaming growth", content2, 'positive')


content3 = """
Behind Apple’s Doomed Car Project: False Starts and Wrong Turns
Internal disagreements over the direction of the Apple car led the effort to sputter for years before it was canceled this week. For the last decade, many Apple employees working on the company’s secretive car project, internally code-named Titan, had a less flattering name for it: the Titanic disaster. They knew the project was likely to fail.
Throughout its existence, the car effort was scrapped and rebooted several times, shedding hundreds of workers along the way. As a result of dueling views among leaders about what an Apple car should be, it began as an electric vehicle that would compete against Tesla and morphed into a self-driving car to rival Google’s Waymo.
By the time of its death — Tuesday, when executives announced internally that the project was being killed and that many members of the team were being reassigned to work on artificial intelligence — Apple had burned more than $10 billion on the project and the car had reverted to its beginnings as an electric vehicle with driving-assistance features rivaling Tesla’s, according to a half dozen people who worked on the project over the past decade.
The car project’s demise was a testament to the way Apple has struggled to develop new products in the years since Steve Jobs’s death in 2011. The effort had four different leaders and conducted multiple rounds of layoffs. But it festered and ultimately fizzled in large part because developing the software and algorithms for a car with autonomous driving features proved too difficult.
"""

article3 = Article(3,"Behind Apple’s Doomed Car Project: False Starts and Wrong Turns", content3,'negative' )

content4 = """
Alphabet’s Google was hit with a €2.1bn ($2.3bn) lawsuit by 32 media groups including Axel Springer and Schibsted on Wednesday, alleging that they had suffered losses due to the company’s practices in digital advertising.
Google’s Gemini AI illustrations of a 1943 German soldier.
Google chief admits ‘biased’ AI tool’s photo diversity offended users
Read moreThe move by the groups – which include publishers in Austria, Belgium, Bulgaria, the Czech Republic, Denmark, Finland, Hungary, Luxembourg, the Netherlands, Norway, Poland, Spain and Sweden – comes as antitrust regulators also crack down on Google’s ad-tech business.
“The media companies involved have incurred losses due to a less competitive market, which is a direct result of Google’s misconduct,” a statement issued by their lawyers, Geradin Partners and Stek, said.
“Without Google’s abuse of its dominant position, the media companies would have received significantly higher revenues from advertising and paid lower fees for ad tech services. Crucially, these funds could have been reinvested into strengthening the European media landscape,” the lawyers said.
"""

article4 = Article(4,"Google sued for $2.3bn by European media groups over digital ad losses", content4, 'negative')


content5 = """
Shoppers are being urged to return a ready meal over fears it could pose a health risk to people with certain allergies.
Scratch Meals Ltd has pulled its Chicken Pad Thai with Noodles & Veggies product as it contains peanuts which could cause potentially serious reactions to those who have a peanut allergy or intolerance. This ingredient is not listed on the label.
For some people with peanut allergy, even tiny amounts of peanuts can cause a serious reaction that can even be life-threatening as it will cause anaphylaxis. Anaphylaxis symptoms can include swelling of the throat that makes it difficult to breathe and a severe drop in blood pressure due to shock - which would require emergency medical attention.
The affected products have the pack size of 380g and the use by dates of January 25, January 26, January 27 and January 28 - all have the use by year 2024. The use by dates can be found on the top panel of the sleeve.
The Scratch ready meal can be bought in both Tesco and Sainsbury's who have both issued their own product recalls. Customers who have bought the product and have a peanut allergy are being advised to return it to the store where it was bought from for a full refund - you will not need a receipt to do this. For further details on the recall, customers can contact the company over the phone on 01472 350197 or by email - hello@mealsfromscratch.co.uk.
In its statement, Scratch Meals has confirmed that no other Scratch product has been affected and has apologised for the inconvenience it may cause.
"""

article5 = Article(5,"Ready meal sold in Tesco and Sainsbury's recalled over fears it could make people sick", content5, 'negative')



content6 = """
Rolls-Royce has entered a game-changing seven-year partnership with Azad Engineering, based in Hyderabad, to manufacture critical components for its defense aircraft engines. This strategic collaboration propels Azad Engineering into the global supply chain for Rolls-Royce’s advanced aero engines, marking a significant leap for India in defense manufacturing. Key figures express optimism, emphasizing the commitment to building a robust presence in India and contributing to the vision of an ‘Atma .. 
Alex Zino, Executive Vice President of Rolls-Royce, expressed satisfaction with the collaboration, stating, “Strong collaboration has been at the heart of Rolls-Royce’s journey of success in India." Zino emphasized the partnership's role in strengthening the defense ecosystem and expanding the supply chain within India. Abhishek Singh, Senior Vice President of Rolls-Royce, echoed this sentiment, noting that the agreement with Azad Engineering is a significant step toward leveraging Indian compan .. 
The strategic partnership aligns with Rolls-Royce's commitment to building a robust presence in India, as Abhishek Singh stated, "This reiterates our commitment to building our presence in India through local partnerships, furthering the vision of an ‘Atmanirbhar Bharat’." Sourcing complex components from India for aero engine programs is viewed as an advancement in enhancing India's capabilities in defense manufacturing. 
"""

article6 = Article(6,"Rolls-Royce inks seven-year deal with Azad Engineering for military aircraft engine components", content6, 'positive')



content7 = """
t's easy to match the overall market return by buying an index fund. Active investors aim to buy stocks that vastly outperform the market - but in the process, they risk under-performance. Unfortunately the JD Sports Fashion Plc (LON:JD.) share price slid 35% over twelve months. That's well below the market decline of 1.3%. Longer term shareholders haven't suffered as badly, since the stock is down a comparatively less painful 26% in three years. Shareholders have had an even rougher run lately, with the share price down 28% in the last 90 days.

The recent uptick of 3.3% could be a positive sign of things to come, so let's take a look at historical fundamentals.

To paraphrase Benjamin Graham: Over the short term the market is a voting machine, but over the long term it's a weighing machine. One imperfect but simple way to consider how the market perception of a company has shifted is to compare the change in the earnings per share (EPS) with the share price movement.

Unfortunately JD Sports Fashion reported an EPS drop of 39% for the last year. This proportional reduction in earnings per share isn't far from the 35% decrease in the share price. Therefore one could posit that the market has not become more concerned about the company, despite the lower EPS. Rather, the share price is remains a similar multiple of the EPS, suggesting the outlook remains the same.
We regret to report that JD Sports Fashion shareholders are down 34% for the year (even including dividends). Unfortunately, that's worse than the broader market decline of 1.3%. However, it could simply be that the share price has been impacted by broader market jitters. It might be worth keeping an eye on the fundamentals, in case there's a good opportunity. Longer term investors wouldn't be so upset, since they would have made 5%, each year, over five years. If the fundamental data continues to indicate long term sustainable growth, the current sell-off could be an opportunity worth considering. While it is well worth considering the different impacts that market conditions can have on the share price, there are other factors that are even more important. To that end, you should be aware of the 3 warning signs we've spotted with JD Sports Fashion .

"""

article7 = Article(7,"The past one-year earnings decline for JD Sports Fashion (LON:JD.) likely explains shareholders long-term losses", content7, 'negative')


content8 = """
March 6 (Reuters) - AstraZeneca (AZN.L), opens new tab plans to invest 650 million pounds ($826.80 million) in Britain to boost research, development and manufacturing of vaccines, the government announced on Wednesday as part of Finance Minister Jeremy Hunt's spring budget.
AstraZeneca's planned investment includes 450 million pounds to research, develop and manufacture vaccines at its manufacturing site in Speke, Liverpool, and another 200 million pounds to expand its existing presence in Cambridge, where its global headquarters are located.
"AstraZeneca’s planned investment would enhance the UK’s pandemic preparedness and demonstrates our ongoing confidence in UK life sciences," the drugmaker's chief Pascal Soriot said in a statement.
The investment is a step change after Soriot shifted a planned new manufacturing plant to Ireland last year, saying that Britain's business climate had deterred biopharma firms from investing in the country.
"AstraZeneca’s investment plans are a vote of confidence," Hunt said.
Britain, in December 2020, was the first country to approve the coronavirus vaccine developed by AstraZeneca and Oxford University.
"""

article8 = Article(8, "AstraZeneca to invest 650 million pounds in UK to boost 'pandemic preparedness'", content8, 'positive')

content9 = """
Shell has refused to comment on a report that it has suspended shipments through the Red Sea amid attacks on freight by Iran-linked Houthi rebels.

The oil and gas major was said, by the Wall Street Journal (WSJ), to have taken the decision last week to avoid the short route to Europe via the Suez Canal indefinitely.

The paper, citing a number of sources, said there was concern within the company that US and UK strikes on Houthi targets in Yemen could be met with further escalation, placing crews and vessels at a greater risk.

The WSJ also reported worries that a successful attack could trigger a massive spill in the region.
Sky News reported last Friday how the cost of a container had leapt by more than 300% since November as prices took account of longer transit times and additional, crew, fuel and insurance costs.
"""

article9 = Article(9, "Shell 'pauses Red Sea shipments indefinitely due to safety risk", content9, 'negative')


content10 = """
Shares of Prudential PLC PRU, -0.28% rallied 2.90% to £7.81 Thursday, on what proved to be an all-around positive trading session for the stock market, with the FTSE 100 Index UKX, -0.43% rising 0.17% to 7,692.46.
Prudential PLC closed £5.15 below its 52-week high (£12.96), which the company achieved on March 9.
Trading volume (6.0 M) remained 2.1 million below its 50-day average volume of 8.1 M.
"""
article10 = Article(10, 'Prudential rises Thursday, outperforms market', content10, 'positive')
articles = [article1, article2, article3, article4, article5, article6, article7, article8, article9, article10]

